// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pembeli.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	pembeli.proto

It has these top-level messages:
	AddPembeliReq
	ReadPembeliResp
	UpdatePembeliReq
	ReadPembeliByKotaReq
	ReadPembeliByKotaResp
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddPembeliReq struct {
	IDPembeli   int32  `protobuf:"varint,1,opt,name=IDPembeli" json:"IDPembeli,omitempty"`
	NamaPembeli string `protobuf:"bytes,2,opt,name=NamaPembeli" json:"NamaPembeli,omitempty"`
	NoTelpon    string `protobuf:"bytes,3,opt,name=NoTelpon" json:"NoTelpon,omitempty"`
	KodeKota    string `protobuf:"bytes,4,opt,name=KodeKota" json:"KodeKota,omitempty"`
	Status      int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreateBy    string `protobuf:"bytes,6,opt,name=CreateBy" json:"CreateBy,omitempty"`
	CreateOn    string `protobuf:"bytes,7,opt,name=CreateOn" json:"CreateOn,omitempty"`
	UpdateOn    string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
	UpdateBy    string `protobuf:"bytes,9,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
}

func (m *AddPembeliReq) Reset()                    { *m = AddPembeliReq{} }
func (m *AddPembeliReq) String() string            { return proto.CompactTextString(m) }
func (*AddPembeliReq) ProtoMessage()               {}
func (*AddPembeliReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddPembeliReq) GetIDPembeli() int32 {
	if m != nil {
		return m.IDPembeli
	}
	return 0
}

func (m *AddPembeliReq) GetNamaPembeli() string {
	if m != nil {
		return m.NamaPembeli
	}
	return ""
}

func (m *AddPembeliReq) GetNoTelpon() string {
	if m != nil {
		return m.NoTelpon
	}
	return ""
}

func (m *AddPembeliReq) GetKodeKota() string {
	if m != nil {
		return m.KodeKota
	}
	return ""
}

func (m *AddPembeliReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddPembeliReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *AddPembeliReq) GetCreateOn() string {
	if m != nil {
		return m.CreateOn
	}
	return ""
}

func (m *AddPembeliReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *AddPembeliReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

type ReadPembeliResp struct {
	AllPembeli []*ReadPembeliByKotaResp `protobuf:"bytes,1,rep,name=allPembeli" json:"allPembeli,omitempty"`
}

func (m *ReadPembeliResp) Reset()                    { *m = ReadPembeliResp{} }
func (m *ReadPembeliResp) String() string            { return proto.CompactTextString(m) }
func (*ReadPembeliResp) ProtoMessage()               {}
func (*ReadPembeliResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadPembeliResp) GetAllPembeli() []*ReadPembeliByKotaResp {
	if m != nil {
		return m.AllPembeli
	}
	return nil
}

type UpdatePembeliReq struct {
	IDPembeli   int32  `protobuf:"varint,1,opt,name=IDPembeli" json:"IDPembeli,omitempty"`
	NamaPembeli string `protobuf:"bytes,2,opt,name=NamaPembeli" json:"NamaPembeli,omitempty"`
	NoTelpon    string `protobuf:"bytes,3,opt,name=NoTelpon" json:"NoTelpon,omitempty"`
	KodeKota    string `protobuf:"bytes,4,opt,name=KodeKota" json:"KodeKota,omitempty"`
	Status      int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreateBy    string `protobuf:"bytes,6,opt,name=CreateBy" json:"CreateBy,omitempty"`
	CreateOn    string `protobuf:"bytes,7,opt,name=CreateOn" json:"CreateOn,omitempty"`
	UpdateOn    string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
	UpdateBy    string `protobuf:"bytes,9,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
}

func (m *UpdatePembeliReq) Reset()                    { *m = UpdatePembeliReq{} }
func (m *UpdatePembeliReq) String() string            { return proto.CompactTextString(m) }
func (*UpdatePembeliReq) ProtoMessage()               {}
func (*UpdatePembeliReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdatePembeliReq) GetIDPembeli() int32 {
	if m != nil {
		return m.IDPembeli
	}
	return 0
}

func (m *UpdatePembeliReq) GetNamaPembeli() string {
	if m != nil {
		return m.NamaPembeli
	}
	return ""
}

func (m *UpdatePembeliReq) GetNoTelpon() string {
	if m != nil {
		return m.NoTelpon
	}
	return ""
}

func (m *UpdatePembeliReq) GetKodeKota() string {
	if m != nil {
		return m.KodeKota
	}
	return ""
}

func (m *UpdatePembeliReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdatePembeliReq) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *UpdatePembeliReq) GetCreateOn() string {
	if m != nil {
		return m.CreateOn
	}
	return ""
}

func (m *UpdatePembeliReq) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *UpdatePembeliReq) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

type ReadPembeliByKotaReq struct {
	KodeKota string `protobuf:"bytes,1,opt,name=KodeKota" json:"KodeKota,omitempty"`
}

func (m *ReadPembeliByKotaReq) Reset()                    { *m = ReadPembeliByKotaReq{} }
func (m *ReadPembeliByKotaReq) String() string            { return proto.CompactTextString(m) }
func (*ReadPembeliByKotaReq) ProtoMessage()               {}
func (*ReadPembeliByKotaReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadPembeliByKotaReq) GetKodeKota() string {
	if m != nil {
		return m.KodeKota
	}
	return ""
}

type ReadPembeliByKotaResp struct {
	IDPembeli   int32  `protobuf:"varint,1,opt,name=IDPembeli" json:"IDPembeli,omitempty"`
	NamaPembeli string `protobuf:"bytes,2,opt,name=NamaPembeli" json:"NamaPembeli,omitempty"`
	NoTelpon    string `protobuf:"bytes,3,opt,name=NoTelpon" json:"NoTelpon,omitempty"`
	KodeKota    string `protobuf:"bytes,4,opt,name=KodeKota" json:"KodeKota,omitempty"`
	Status      int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreateBy    string `protobuf:"bytes,6,opt,name=CreateBy" json:"CreateBy,omitempty"`
	CreateOn    string `protobuf:"bytes,7,opt,name=CreateOn" json:"CreateOn,omitempty"`
	UpdateOn    string `protobuf:"bytes,8,opt,name=UpdateOn" json:"UpdateOn,omitempty"`
	UpdateBy    string `protobuf:"bytes,9,opt,name=UpdateBy" json:"UpdateBy,omitempty"`
}

func (m *ReadPembeliByKotaResp) Reset()                    { *m = ReadPembeliByKotaResp{} }
func (m *ReadPembeliByKotaResp) String() string            { return proto.CompactTextString(m) }
func (*ReadPembeliByKotaResp) ProtoMessage()               {}
func (*ReadPembeliByKotaResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadPembeliByKotaResp) GetIDPembeli() int32 {
	if m != nil {
		return m.IDPembeli
	}
	return 0
}

func (m *ReadPembeliByKotaResp) GetNamaPembeli() string {
	if m != nil {
		return m.NamaPembeli
	}
	return ""
}

func (m *ReadPembeliByKotaResp) GetNoTelpon() string {
	if m != nil {
		return m.NoTelpon
	}
	return ""
}

func (m *ReadPembeliByKotaResp) GetKodeKota() string {
	if m != nil {
		return m.KodeKota
	}
	return ""
}

func (m *ReadPembeliByKotaResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadPembeliByKotaResp) GetCreateBy() string {
	if m != nil {
		return m.CreateBy
	}
	return ""
}

func (m *ReadPembeliByKotaResp) GetCreateOn() string {
	if m != nil {
		return m.CreateOn
	}
	return ""
}

func (m *ReadPembeliByKotaResp) GetUpdateOn() string {
	if m != nil {
		return m.UpdateOn
	}
	return ""
}

func (m *ReadPembeliByKotaResp) GetUpdateBy() string {
	if m != nil {
		return m.UpdateBy
	}
	return ""
}

func init() {
	proto.RegisterType((*AddPembeliReq)(nil), "grpc.AddPembeliReq")
	proto.RegisterType((*ReadPembeliResp)(nil), "grpc.ReadPembeliResp")
	proto.RegisterType((*UpdatePembeliReq)(nil), "grpc.UpdatePembeliReq")
	proto.RegisterType((*ReadPembeliByKotaReq)(nil), "grpc.ReadPembeliByKotaReq")
	proto.RegisterType((*ReadPembeliByKotaResp)(nil), "grpc.ReadPembeliByKotaResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for PembeliService service

type PembeliServiceClient interface {
	AddPembeli(ctx context.Context, in *AddPembeliReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadPembeli(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadPembeliResp, error)
	UpdatePembeli(ctx context.Context, in *UpdatePembeliReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadPembeliByKota(ctx context.Context, in *ReadPembeliByKotaReq, opts ...grpc1.CallOption) (*ReadPembeliByKotaResp, error)
}

type pembeliServiceClient struct {
	cc *grpc1.ClientConn
}

func NewPembeliServiceClient(cc *grpc1.ClientConn) PembeliServiceClient {
	return &pembeliServiceClient{cc}
}

func (c *pembeliServiceClient) AddPembeli(ctx context.Context, in *AddPembeliReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.PembeliService/AddPembeli", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pembeliServiceClient) ReadPembeli(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadPembeliResp, error) {
	out := new(ReadPembeliResp)
	err := grpc1.Invoke(ctx, "/grpc.PembeliService/ReadPembeli", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pembeliServiceClient) UpdatePembeli(ctx context.Context, in *UpdatePembeliReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.PembeliService/UpdatePembeli", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pembeliServiceClient) ReadPembeliByKota(ctx context.Context, in *ReadPembeliByKotaReq, opts ...grpc1.CallOption) (*ReadPembeliByKotaResp, error) {
	out := new(ReadPembeliByKotaResp)
	err := grpc1.Invoke(ctx, "/grpc.PembeliService/ReadPembeliByKota", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PembeliService service

type PembeliServiceServer interface {
	AddPembeli(context.Context, *AddPembeliReq) (*google_protobuf.Empty, error)
	ReadPembeli(context.Context, *google_protobuf.Empty) (*ReadPembeliResp, error)
	UpdatePembeli(context.Context, *UpdatePembeliReq) (*google_protobuf.Empty, error)
	ReadPembeliByKota(context.Context, *ReadPembeliByKotaReq) (*ReadPembeliByKotaResp, error)
}

func RegisterPembeliServiceServer(s *grpc1.Server, srv PembeliServiceServer) {
	s.RegisterService(&_PembeliService_serviceDesc, srv)
}

func _PembeliService_AddPembeli_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPembeliReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PembeliServiceServer).AddPembeli(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PembeliService/AddPembeli",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PembeliServiceServer).AddPembeli(ctx, req.(*AddPembeliReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PembeliService_ReadPembeli_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PembeliServiceServer).ReadPembeli(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PembeliService/ReadPembeli",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PembeliServiceServer).ReadPembeli(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PembeliService_UpdatePembeli_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePembeliReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PembeliServiceServer).UpdatePembeli(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PembeliService/UpdatePembeli",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PembeliServiceServer).UpdatePembeli(ctx, req.(*UpdatePembeliReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PembeliService_ReadPembeliByKota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPembeliByKotaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PembeliServiceServer).ReadPembeliByKota(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PembeliService/ReadPembeliByKota",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PembeliServiceServer).ReadPembeliByKota(ctx, req.(*ReadPembeliByKotaReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PembeliService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.PembeliService",
	HandlerType: (*PembeliServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddPembeli",
			Handler:    _PembeliService_AddPembeli_Handler,
		},
		{
			MethodName: "ReadPembeli",
			Handler:    _PembeliService_ReadPembeli_Handler,
		},
		{
			MethodName: "UpdatePembeli",
			Handler:    _PembeliService_UpdatePembeli_Handler,
		},
		{
			MethodName: "ReadPembeliByKota",
			Handler:    _PembeliService_ReadPembeliByKota_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "pembeli.proto",
}

func init() { proto.RegisterFile("pembeli.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xa6, 0xe5, 0x47, 0x18, 0x82, 0x3f, 0xab, 0x90, 0x4d, 0xf1, 0x40, 0xf6, 0xc4, 0xa9, 0x24,
	0x78, 0x34, 0x31, 0xa1, 0xea, 0xc1, 0x90, 0x14, 0x53, 0xf4, 0x01, 0x16, 0xba, 0x12, 0x92, 0xc2,
	0x2e, 0xa5, 0x98, 0xf4, 0x29, 0x4c, 0xbc, 0x78, 0xf5, 0x51, 0xcd, 0x76, 0x5b, 0xda, 0xca, 0xcf,
	0x0b, 0xe8, 0xf1, 0xdb, 0x6f, 0x66, 0x67, 0xf6, 0xdb, 0xf9, 0x06, 0x1a, 0x82, 0x2d, 0x26, 0xcc,
	0x9b, 0x9b, 0xc2, 0xe7, 0x01, 0x47, 0xa5, 0x99, 0x2f, 0xa6, 0x46, 0x7b, 0xc6, 0xf9, 0xcc, 0x63,
	0xbd, 0xe8, 0x6c, 0xb2, 0x79, 0xeb, 0xb1, 0x85, 0x08, 0x42, 0x15, 0x42, 0x3e, 0x74, 0x68, 0x0c,
	0x5c, 0xf7, 0x59, 0xe5, 0x39, 0x6c, 0x85, 0xae, 0xa1, 0xf6, 0xf4, 0x10, 0x63, 0xac, 0x75, 0xb4,
	0x6e, 0xd9, 0x49, 0x0f, 0x50, 0x07, 0xea, 0x36, 0x5d, 0xd0, 0x84, 0xd7, 0x3b, 0x5a, 0xb7, 0xe6,
	0x64, 0x8f, 0x90, 0x01, 0x55, 0x9b, 0xbf, 0x30, 0x4f, 0xf0, 0x25, 0x2e, 0x46, 0xf4, 0x16, 0x4b,
	0x6e, 0xc8, 0x5d, 0x36, 0xe4, 0x01, 0xc5, 0x25, 0xc5, 0x25, 0x18, 0xb5, 0xa0, 0x32, 0x0e, 0x68,
	0xb0, 0x59, 0xe3, 0x72, 0x54, 0x34, 0x46, 0x32, 0xe7, 0xde, 0x67, 0x34, 0x60, 0x56, 0x88, 0x2b,
	0x2a, 0x27, 0xc1, 0x29, 0x37, 0x5a, 0xe2, 0x93, 0x2c, 0x37, 0x8a, 0x6a, 0xbd, 0x0a, 0x57, 0x71,
	0x55, 0xc5, 0x25, 0x38, 0xe5, 0xac, 0x10, 0xd7, 0xb2, 0x9c, 0x15, 0x12, 0x1b, 0xce, 0x1c, 0x46,
	0x53, 0x45, 0xd6, 0x02, 0xdd, 0x02, 0x50, 0xcf, 0x4b, 0x35, 0x29, 0x76, 0xeb, 0xfd, 0xb6, 0x29,
	0xc5, 0x35, 0x33, 0xa1, 0x56, 0x28, 0xdf, 0x21, 0x13, 0x9c, 0x4c, 0x38, 0xf9, 0xd4, 0xe1, 0x5c,
	0x5d, 0xfe, 0x2f, 0xf2, 0x56, 0xe4, 0x3e, 0x5c, 0xed, 0x51, 0x6e, 0x95, 0xeb, 0x5d, 0xcb, 0xf7,
	0x4e, 0xbe, 0x74, 0x68, 0xee, 0x95, 0xfb, 0xaf, 0xab, 0xd9, 0xff, 0xd6, 0xe1, 0x34, 0x7e, 0xcb,
	0x98, 0xf9, 0xef, 0xf3, 0x29, 0x93, 0x23, 0x9b, 0xda, 0x1a, 0x5d, 0xaa, 0x61, 0xcd, 0x19, 0xdd,
	0x68, 0x99, 0x6a, 0x31, 0x98, 0xc9, 0x62, 0x30, 0x1f, 0xe5, 0x62, 0x20, 0x05, 0x74, 0x07, 0xf5,
	0x8c, 0xd0, 0xe8, 0x40, 0xa0, 0xd1, 0xdc, 0xb1, 0x80, 0xfc, 0x0d, 0x52, 0x40, 0x03, 0x68, 0xe4,
	0x26, 0x5e, 0xde, 0x20, 0x23, 0x7f, 0xdb, 0xe0, 0x48, 0x0b, 0x36, 0x5c, 0xec, 0xfc, 0x35, 0x32,
	0x0e, 0x7a, 0x6e, 0x65, 0x1c, 0xf3, 0x23, 0x29, 0x4c, 0x2a, 0x51, 0x85, 0x9b, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0x4b, 0x2d, 0xde, 0x22, 0x05, 0x00, 0x00,
}
